# .streamlit/secrets.toml
fred_api_key = "80e404935b9ca503ebdfa01c2e7a56f3"
openai_api_key = "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"